### ISSUE TITLE
Reduce number of for loops and use generators

### ISSUE THREAD

**Issue by djhoese** [alttch/rapidtables#1]
I was the guy bugging you on reddit. I was going to make a pull request that incorporated generators more, but got a little confused by some of the logic in `format_table`. This for loop could really benefit from being turned in to a generator:

https://github.com/alttch/rapidtables/blob/e96d9d68744ff106f889d95b97fa51cf16830bb0/rapidtables/__init__.py#L58-L78

However, the outer for loop is on the header keys and more importantly the `key_lengths` logic requires looking at every value to be printed. Before I understood what the `key_lengths` stuff was actually doing I was wondering if it could be moved. Now that I see what you're doing (finding the width of each column), I'm not sure there is a better way.

Here's what I was going to try to contribute:

```python
table_iter = iter(table)
first_row = next(table_iter)
keys = tuple(first_row)
len_keys = len(keys)

formatted_tuples = format_values(first_row, table_iter)  # generator

if generate_header:
    ...
else:
    ...

result = body_generator(formatted_tuples)
... returns ...

```

I realized that your README says you aren't planning on being fast for large numbers of rows, but I think something like this could still perform well. This way it would only iterate over the entire input data once.

Also, you may want to test moving the body_generator outside the function and pass all of the variables used. I'm not sure on the performance differences between local variables and outer scope variables, but I would think local variables would be faster.

**Comment by divi255** [comment]
this loop walks over the whole dict, calculates max. column lengths and checks is value numeric (for alignment). during that it also converts a dict to the tuple of tuples. I've made a generator in the next loop, which outputs the result

**Comment by divi255** [comment]
I understand what you are talking about, with the current implementation the dict is transformed to tuple of cols:

(('John', 'Jack', 'Diana', 'Ken'), ('2000', '2500', '', '1800'), ('DevOps', 'Architect', 'Student', 'Q/A'))

this is required to quickly calculate max length. after, the output loop uses it. I don't think we can put generator here, at least this part should be rewritten

**Comment by djhoese** [comment]
Right, you can't get a width for each column so that *all* data fits in the column nicely without checking every value's width. The code could "guess" based on the first row, or allow the user to provide a width for each column, or something similar. Obviously avoiding how many times the data table has to be iterated over would make it faster. Passing a generator to a generator would be even better.

**Comment by divi255** [comment]
I've already rewrote this part and got rid of vals() tuple. now it's 5x times faster than pandas on 10k row test table. Finishing 100k test now

**Comment by divi255** [comment]
https://raw.githubusercontent.com/alttch/rapidtables/master/benchmark.png

I guess much better now

**Comment by divi255** [comment]
I'm not guru in pandas, but afaik dataframe created from dict can't be properly printed if you don't set index column - the internal index will be printed instead

but if you leave only 

df = pandas.DataFrame(data=table)
return df.to_string()

result will be almost the same even with such head start

**Comment by djhoese** [comment]
I meant the creation of the DataFrame itself. If you assume someone who asks "should I use rapidtables or pandas?", if they already have a pandas DataFrame that they were working with then the creation and conversion to a DataFrame from a dict is already part of their workflow.

**Comment by divi255** [comment]
I've even tried to test df.to_string() only, pandas is still 5x slower. but that's unfair - dataframe is their own format and of course they work with it better

but don't forget pandas is a great data harvester while rapidtables can solve only one particular case )

**Comment by divi255** [comment]
well let's give pandas a bigger head start:

we have a dataframe

def test_pandas(): return df.to_string()
def test_rapidtables(): return rapidtables.make_table(df.to_dict('records'))

and pandas is still 3x slower on a small tables and 1.5x slower on large
