### ISSUE TITLE
`body_generator() takes 0 positional arguments` when using 0 fmt

### ISSUE THREAD

**Issue by Ronserruya** [alttch/rapidtables#2]
```python
rapidtables.format_table(table=data, fmt=0)
```

```
    result += '\n'.join(body_generator(False))
TypeError: body_generator() takes 0 positional arguments but 1 was given
```

Happens [here](https://github.com/alttch/rapidtables/blob/a8e66fa8b3a713ac6a659ac35216b95c1dbda996/rapidtables/__init__.py#L146), body_generator is called with "False".

**Comment by divi255** [comment]
thanks, fixed. that's strange it worked in 3.7 with this )
