### ISSUE TITLE
Request: Asciidoctor table

### ISSUE THREAD

**Issue by ahaeberle** [alttch/rapidtables#8]
Asciidoctor is the new kid In town or an old one reborn. Would you be interested to integrate this format to the project?

Feel free to reject 
Felix

**Comment by divi255** [comment]
u mean asciidoctor tables?
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables

**Comment by ahaeberle** [comment]
Yes that’s it

**Comment by divi255** [comment]
added "asciidoc" table type for make/print_table in 0.1.11
